server:
  port: 8090
#  port: 443
#  ssl:
#    key-alias: tomcat
#    key-store: classpath:keystore.p12
#    key-store-password: tomcat
#    key-store-type: PKCS12

spring:
  druid:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: zhihu
    password: zhihu
    maxActive: 30 #最小连接数
    minIdle: 5 #最大连接数
    maxWait: 10000 #获取连接的的最大等待时间
    timeBetweenEvictionRunsMillis: 6000 #空闲连接检查时间间隔
    minEvictableIdleTimeMillis: 300000 #空闲连接的最小空闲时间pompokm,
  mail:
    host: smtp.office365.com
    username: ENC(/aj0rf5PWJp7Vlf/OgbsQPXaOGVOOdtr+4f6wzlhNcU=)
    password: ENC(CtOqcyMw5DQf4YVwu9I3Y4OCQlzhd6Ho)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  rabbitmq:
    username: ENC(E5R3ZojVQGrWtr7uS6qHZw==)
    password: ENC(m6e+cwbN8Ueruc+lAOPjFA==)
    host: ENC(UiZTlQTFdQRA5ms53lgyrXKnCEMT53WU)
    port: 5672
    virtual-host: /
    #    开启手动ACK 不开启自动ACk模式 目的是防止报错后未正确处理消息丢失 默认为inone
    listener:
      simple:
        acknowledge-mode: manual


mybatis:
  type-aliases-package: com.zhihu.demo.model #给包中的类注册别名，注册后可以直接使用类名，而不用使用全限定的类名（就是不用包含包名）。
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名转换
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    jdbc-type-for-null: NULL
  mapper-locations: mapper/*.xml #mapper文件

#constant
com:
  zhihu:
    demo:
      constant:
        salt: sugar # 密码盐
        expire: 3600000 # 60*60*1000 token过期时间为一小时
        refresh: 2592000000 #30*24*60*60*1000 token刷新有效期为一个月
        secret: hard_to_guess_string #用于颁发token的密钥 原是用用户的密码作为密钥加密 但那每次会引起不必要的数据库查询 TODO 也许应该加上定期更换密钥的策略
#redis
redis:
  host: ENC(WUM1EDmvyumpz+l2Ac7KxKgTOH6RFTCW)
  port: 6379
  timeout: 3
  password: ENC(bR8G8TrIvDJyYW0wsPD+AnP86ADbsGNJ)
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3

# 配置文件加密key
jasypt:
  encryptor:
    password: ${SECRET_KEY}


